#! /bin/bash



#Get Arguments
SOURCE_ID="${1:?[Arg1 missing] Enter source artifactory server ID}"
TARGET_ID="${2:?[Arg2 Missing] ]Enter target artifactory server ID}"

# Below are the list of files that are generated by Jfrog Artifactory. So these will be ignored
#skippedfiles=("repository.catalog") 
skippedfiles=("repository.catalog" "maven-metadata.xml"  "Packages.bz2"  ".gemspec.rz" "Packages.gz"  "Release"  ".json"  "Packages"  "by-hash"  "filelists.xml.gz"  "other.xml.gz"  "primary.xml.gz"  "repomd.xml"  "repomd.xml.asc"  "repomd.xml.key")
runtask() {
mkdir -p "$output/folder/$1"
cd "$output/folder/$1"
jf rt curl -s -XPOST -H 'Content-Type: text/plain' api/search/aql --server-id $SOURCE_ID --data "items.find({\"repo\": \"$1\"}).include(\"repo\",\"path\",\"name\",\"sha256\")" | jq '.results[]|(.path +"/"+ .name+","+(.sha256|tostring))' | sed  's/\.\///' > a
jf rt curl -s -XPOST -H 'Content-Type: text/plain' api/search/aql --server-id $TARGET_ID --data "items.find({\"repo\": \"$1\"}).include(\"repo\",\"path\",\"name\",\"sha256\")" | jq '.results[]|(.path +"/"+ .name+","+(.sha256|tostring))' | sed  's/\.\///' > b
comm -23  <(sort a) <(sort b) | sed -re 's/,[[:alnum:]]+"$/"/g' |sed 's/"//g' > c
#cat c | xargs -I {} echo "jf rt dl \"$1/{}\" . --server-id local ; jf rt u \"{}\" \"$1/{}\" --server-id local1 ; rm -f \"{}\" "
cat -b c >> fulllist.log
file_path="c"

# Check if the file exists
if [ -e "$file_path" ]; then
    # Check if the file is not empty
    if [ -s "$file_path" ]; then
       while IFS= read -r line; do
	 bname=$(echo $line | rev | cut -d"/" -f1 | rev)
         matched=false
         if [[ "$line" =~ ^.npm|^.jfrog|^.pypi|^.composer|^index.yaml$|^versions$|_uploads|xml.gz$ ]]; then
           matched=true;
         else
           for element in "${skippedfiles[@]}"; do
              if [[ "$element" == $bname ]]; then
                  matched=true;
              fi
          done
         fi 
         if [[ "$matched" == 'false' ]]; then
            echo $line >> d
	    echo "jf rt dl \"$1/$line\" . --server-id $SOURCE_ID ; jf rt u \"$line\" \"$1/$line\" --server-id $TARGET_ID  ; rm -f \"$line\" " >> "transfer.txt"
         fi
       done < $file_path
       if [ -s "d" ]; then
         echo "-------------------------------------------------" > "$1.txt"
         echo "Files diff from source - Repo [$1]" >> "$1.txt"
         echo "-------------------------------------------------" >> "$1.txt"
         cat -b d >> "$1.txt"
       fi
    fi
fi
}
 
output=out_$(date +%s) 
rm -f fulllist.log
mkdir -p $output
N=10
i=1
for art in $(jf rt curl -s -XGET '/api/repositories?type=local' --server-id  $SOURCE_ID | jq -r '.[] | .key');
do
	if [[ "$art" == "artifactory-build-info" ]]; then
		        continue
	fi
   echo "Running Diff for Repo [$art]"
   runtask $art &
   ((i=i%N)); ((i++==0)) && wait
done
